apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gitlab-runners
  name: gitlab-runner
rules:
- apiGroups: [""]
  resources: ["secrets", "pods", "pods/exec", "pods/attach"]
  verbs: ["*"]
